# This workflow runs when a merge to master is performed. It will
# run the unit tests and create a github release based on
# the commit messages being in the conventional commits format.
# If a release is created, the publish workflow
# will be called, which will create and attach the binaries and deploy to spinnaker.
name: release

on:
  push:
    branches:
      - 'master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'github commit, branch, or tag'

env:
  RELEASE_DOCKER_REGISTRY: kumo-docker-release-local.artylab.expedia.biz

jobs:
  release:
    runs-on: eg-default
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      -
        name: Create tag and release
        run: |
          npm install semantic-release semantic-release/git
          npx semantic-release --debug --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_GITHUB_TOKEN }}
          GITHUB_URL: https://github.expedia.biz
